import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import pandas as pd
import numpy as np
import sys
import os
import argparse
from tqdm import tqdm
from sklearn.metrics import accuracy_score, classification_report

# Setup Path
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(project_root)
sys.path.append(os.path.join(project_root, 'src', 'engine_b_signal'))

# Imports
from src.config import STAGE2_DATA_PATH, STAGE2_MODEL_PATH
from src.engine_b_signal.train_signal_model import DATA_DIR, NUM_LEADS
from src.engine_b_signal.models.resnet1d_se import SEResNet34

# Config
BATCH_SIZE = 32
EPOCHS = 15
LEARNING_RATE = 1e-4
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class RouterDataset(Dataset):
    def __init__(self, csv_file, root_dir, seq_len=5000):
        self.data_frame = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.seq_len = seq_len
        
    def __len__(self):
        return len(self.data_frame)
    
    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
            
        row = self.data_frame.iloc[idx]
        
        # Load Signal
        # Filename logic usually involves checking extension
        filename = row['filename'] if 'filename' in row else row['scp_codes'] # Fallback? 
        # Actually existing dataset relies on 'filename_lr' or 'filename_hr' usually
        # Let's assume 'filename_lr' exists or construct path.
        # Original CSV_PATH points to a file that has valid path info.
        # Since we copied rows, we have the same columns.
        
        # Typical logic from ECGSignalDataset:
        # path = os.path.join(self.root_dir, filename)
        # Note: The data prep script copies the row, so columns are preserved.
        
        # Need to handle relative path if dataset does.
        # Let's try standard column 'filename_hr' if avail, else 'filename_lr'
        fname = row.get('filename_hr', row.get('filename_lr'))
        if not isinstance(fname, str):
             fname = str(fname)
             
        file_path = os.path.join(self.root_dir, fname)
        
        # Load .npy
        try:
            # We assume .npy files exist as generated by data synthesis
            # Usually they are in data/output/signals/
            # If path in CSV is relative to a base, we need to respect that.
            # Let's try loading.
            
            # If file extension missing, add .npy? 
            # Original code: np.load(os.path.join(self.root_dir, self.data_frame.iloc[idx, 0])) 
            # if col 0 is path.
            
            if not file_path.endswith('.npy'):
                 file_path += '.npy'
                 
            signal = np.load(file_path)
            
        except Exception as e:
            # print(f"Error loading {file_path}: {e}")
            # Return zero tensor fallback
            signal = np.zeros((12, self.seq_len))
            
        # Processing
        # 1. Transpose if (5000, 12) -> (12, 5000)
        if signal.shape[0] != 12 and signal.shape[1] == 12:
            signal = signal.T
            
        # 2. Length handling
        current_len = signal.shape[1]
        if current_len != self.seq_len:
            # Resample or Crop/Pad
            # Linear Interpolation
            sig_torch = torch.tensor(signal, dtype=torch.float32).unsqueeze(0)
            sig_torch = torch.nn.functional.interpolate(sig_torch, size=self.seq_len, mode='linear')
            signal = sig_torch.squeeze(0).numpy()
            
        # 3. Router Label
        label = int(row['router_label'])
        
        return torch.tensor(signal, dtype=torch.float32), torch.tensor(label, dtype=torch.long)

def train_router():
    print("--- Starting Stage 2 Training: The Router ---")
    
    # 1. Data
    print(f"Loading Prepared Data from {STAGE2_DATA_PATH}...")
    if not os.path.exists(STAGE2_DATA_PATH):
        print("CRITICAL: Data file not found. Run prepare_stage2_data.py first.")
        return
        
    dataset = RouterDataset(csv_file=STAGE2_DATA_PATH, root_dir=DATA_DIR)
    
    train_size = int(0.8 * len(dataset))
    val_size = len(dataset) - train_size
    generator = torch.Generator().manual_seed(42)
    train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size], generator=generator)
    
    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=4)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4)
    
    # 2. Model
    # Binary: Rhythm (0) vs Structure (1)
    model = SEResNet34(num_classes=2, input_channels=NUM_LEADS)
    model = model.to(DEVICE)
    
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-3)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
    
    best_acc = 0.0
    
    for epoch in range(EPOCHS):
        model.train()
        train_loss = 0
        
        pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)
        for inputs, labels in pbar:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
            
        scheduler.step()
        
        # Validation
        model.eval()
        all_preds = []
        all_labels = []
        
        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
                outputs = model(inputs)
                _, predicted = torch.max(outputs.data, 1)
                
                all_preds.extend(predicted.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())
                
        acc = accuracy_score(all_labels, all_preds)
        print(f"Epoch {epoch+1} | Loss: {train_loss/len(train_loader):.4f} | Acc: {acc:.2%}")
        
        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), STAGE2_MODEL_PATH)
            print("  -> Saved Best Model")
            
    # Final Report
    print(f"\nTraining Complete. Best Accuracy: {best_acc:.2%}")
    print(classification_report(all_labels, all_preds, target_names=["Rhythm", "Structure"]))

if __name__ == "__main__":
    train_router()
